name: expense_tracker
description: A Flutter app for tracking expenses

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=2.19.0 <3.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  path_provider: ^2.0.14
  file_picker: ^8.0.5
  csv: ^5.1.1
  fl_chart: ^0.68.0
  provider: ^6.0.5
  isar: ^3.0.0
  isar_flutter_libs: ^3.0.0
  intl: ^0.17.0
  flutter_slidable: ^3.1.0
  ml_algo: ^16.15.1
  ml_dataframe: ^1.6.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0
  isar_generator: ^3.0.0
  build_runner: ^2.1.11

  

flutter:
  uses-material-design: true